seeder:
  file: "./seeder/seeder.rb"
  disabled: false

parsers:
  - page_type: categories 
    file: "./parsers/categories.rb"
    disabled: true
  - page_type: sidebar_categories 
    file: "./parsers/sidebar_categories.rb"
    disabled: false
  - page_type: listings
    file: "./parsers/listings.rb"
    disabled: false


exporters:
  - file: "./exporters/product_json.yaml"
    disabled: false
  - file: "./exporters/product_csv.yaml"
    disabled: false

parse_failed_pages: true